### ISSUE TITLE
code problems 

### ISSUE THREAD

**Issue by TunnelThruTime** [rr-/drill#4]
Traceback (most recent call last):
  File "/usr/local/bin/drill-srs", line 6, in <module>
    from drillsrs.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/drillsrs/__main__.py", line 41
    commands: List[cmd.CommandBase],
            ^
SyntaxError: invalid syntax

**Comment by rr-** [comment]
This project requires Python 3
